#include "apriori.h"


char numerals[NUMERALS_NUM*2][WORD_LEN] = {
	// CARDINAL NUMERALS
    "nul",     "zero"             CARD NUM ")",
	"unu",     "one"              CARD NUM ")",
	"du",      "two"              CARD NUM ")",
	"tri",     "three"            CARD NUM ")",
	"kvar",    "four"             CARD NUM ")",
	"kvin",    "five"             CARD NUM ")",
	"ses",     "six"              CARD NUM ")",
	"sep",     "seven"            CARD NUM ")",
	"ok",      "eight"            CARD NUM ")",
	"naŭ",     "nine"             CARD NUM ")",
	"dek",     "ten"              CARD NUM ")",
	"cent",    "hundred"          CARD NUM ")",
	"mil",     "thousand"         CARD NUM ")",


	// ORDINAL NUMERALS
    "nula",     "zeroth"          ORD NUM SING NOM,
	"unua",     "first"           ORD NUM SING NOM,
	"dua",      "second"          ORD NUM SING NOM,
	"tria",     "third"           ORD NUM SING NOM,
	"kvara",    "fourth"          ORD NUM SING NOM,
	"kvina",    "fifth"           ORD NUM SING NOM,
	"sesa",     "sixth"           ORD NUM SING NOM,
    "sepa",     "seventh"         ORD NUM SING NOM,
	"oka",      "eighth"          ORD NUM SING NOM,
	"naŭa",     "ninth"           ORD NUM SING NOM,
	"deka",     "tenth"           ORD NUM SING NOM,
	"centa",    "hundredth"       ORD NUM SING NOM,
	"mila",     "thousandth"      ORD NUM SING NOM,

    "nulaj",    "zeroth"          ORD NUM PLUR NOM,
	"unuaj",    "first"           ORD NUM PLUR NOM,
	"duaj",     "second"          ORD NUM PLUR NOM,
	"triaj",    "third"           ORD NUM PLUR NOM,
	"kvaraj",   "fourth"          ORD NUM PLUR NOM,
	"kvinaj",   "fifth"           ORD NUM PLUR NOM,
	"sesaj",    "sixth"           ORD NUM PLUR NOM,
    "sepaj",    "seventh"         ORD NUM PLUR NOM,
	"okaj",     "eighth"          ORD NUM PLUR NOM,
	"naŭaj",    "ninth"           ORD NUM PLUR NOM,
	"dekaj",    "tenth"           ORD NUM PLUR NOM,
	"centaj",   "hundredth"       ORD NUM PLUR NOM,
	"milaj",    "thousandth"      ORD NUM PLUR NOM,

    "nulan",    "zeroth"          ORD NUM SING ACC,
	"unuan",    "first"           ORD NUM SING ACC,
	"duan",     "second"          ORD NUM SING ACC,
	"trian",    "third"           ORD NUM SING ACC,
	"kvaran",   "fourth"          ORD NUM SING ACC,
	"kvinan",   "fifth"           ORD NUM SING ACC,
	"sesan",    "sixth"           ORD NUM SING ACC,
    "sepan",    "seventh"         ORD NUM SING ACC,
	"okan",     "eighth"          ORD NUM SING ACC,
	"naŭan",    "ninth"           ORD NUM SING ACC,
	"dekan",    "tenth"           ORD NUM SING ACC,
	"centan",   "hundredth"       ORD NUM SING ACC,
	"milan",    "thousandth"      ORD NUM SING ACC,

    "nulajn",   "zeroth"          ORD NUM PLUR ACC,
	"unuajn",   "first"           ORD NUM PLUR ACC,
	"duajn",    "second"          ORD NUM PLUR ACC,
	"triajn",   "third"           ORD NUM PLUR ACC,
	"kvarajn",  "fourth"          ORD NUM PLUR ACC,
	"kvinajn",  "fifth"           ORD NUM PLUR ACC,
	"sesajn",   "sixth"           ORD NUM PLUR ACC,
    "sepajn",   "seventh"         ORD NUM PLUR ACC,
	"okajn",    "eighth"          ORD NUM PLUR ACC,
	"naŭajn",   "ninth"           ORD NUM PLUR ACC,
	"dekajn",   "tenth"           ORD NUM PLUR ACC,
	"centajn",  "hundredth"       ORD NUM PLUR ACC,
	"milajn",   "thousandth"      ORD NUM PLUR ACC,

	
	// SUBSTANTIVIZED NUMERALS
    "nulo",     "zero"            SUBZ NUM SING NOM,
	"unuo",     "one"             SUBZ NUM SING NOM,
	"duo",      "two"             SUBZ NUM SING NOM,
	"trio",     "three"           SUBZ NUM SING NOM,
	"kvaro",    "four"            SUBZ NUM SING NOM,
	"kvino",    "five"            SUBZ NUM SING NOM,
	"seso",     "six"             SUBZ NUM SING NOM,
    "sepo",     "seven"           SUBZ NUM SING NOM,
	"oko",      "eigh"            SUBZ NUM SING NOM,
	"naŭo",     "nin"             SUBZ NUM SING NOM,
	"deko",     "ten"             SUBZ NUM SING NOM,
	"cento",    "hundred"         SUBZ NUM SING NOM,
	"milo",     "thousand"        SUBZ NUM SING NOM,

    "nuloj",    "zeroes"          SUBZ NUM PLUR NOM,
	"unuoj",    "ones"            SUBZ NUM PLUR NOM,
	"duoj",     "twos"            SUBZ NUM PLUR NOM,
	"trioj",    "threes"          SUBZ NUM PLUR NOM,
	"kvaroj",   "fours"           SUBZ NUM PLUR NOM,
	"kvinoj",   "fives"           SUBZ NUM PLUR NOM,
	"sesoj",    "sixes"           SUBZ NUM PLUR NOM,
    "sepoj",    "sevens"          SUBZ NUM PLUR NOM,
	"okoj",     "eights"          SUBZ NUM PLUR NOM,
	"naŭoj",    "nines"           SUBZ NUM PLUR NOM,
	"dekoj",    "tens"            SUBZ NUM PLUR NOM,
	"centoj",   "hundreds"        SUBZ NUM PLUR NOM,
	"miloj",    "thousands"       SUBZ NUM PLUR NOM,

    "nulon",    "zero"            SUBZ NUM SING ACC,
	"unuon",    "one"             SUBZ NUM SING ACC,
	"duon",     "two"             SUBZ NUM SING ACC,
	"trion",    "three"           SUBZ NUM SING ACC,
	"kvaron",   "four"            SUBZ NUM SING ACC,
	"kvinon",   "five"            SUBZ NUM SING ACC,
	"seson",    "six"             SUBZ NUM SING ACC,
    "sepon",    "seven"           SUBZ NUM SING ACC,
	"okon",     "eight"           SUBZ NUM SING ACC,
	"naŭon",    "nine"            SUBZ NUM SING ACC,
	"dekon",    "ten"             SUBZ NUM SING ACC,
	"centon",   "hundred"         SUBZ NUM SING ACC,
	"milon",    "thousand"        SUBZ NUM SING ACC,

    "nulojn",   "zeroes"          SUBZ NUM PLUR ACC,
	"unuojn",   "ones"            SUBZ NUM PLUR ACC,
	"duojn",    "twos"            SUBZ NUM PLUR ACC,
	"triojn",   "threes"          SUBZ NUM PLUR ACC,
	"kvarojn",  "fours"           SUBZ NUM PLUR ACC,
	"kvinojn",  "fives"           SUBZ NUM PLUR ACC,
	"sesojn",   "sixes"           SUBZ NUM PLUR ACC,
    "sepojn",   "sevens"          SUBZ NUM PLUR ACC,
	"okojn",    "eights"          SUBZ NUM PLUR ACC,
	"naŭojn",   "nines"           SUBZ NUM PLUR ACC,
	"dekojn",   "tens"            SUBZ NUM PLUR ACC,
	"centojn",  "hundreds"        SUBZ NUM PLUR ACC,
	"milojn",   "thousands"       SUBZ NUM PLUR ACC,
};
